#!/usr/bin/env bash

# Install the dependencies for the dotfiles-openjck-setup script, then run it.
#
# The dotfiles-openjck-setup script is written in Python. The Python tool "uv"
# is used to ensure that the correct version of Python is installed, as well as
# all Python packages that the script depends on. For that reason, uv must be
# installed before running the script. This script installs uv.
#
# The dotfiles-openjck-setup script installs docopts, so docopts is not used in
# this script itself.

# MIT License
#
# Copyright (c) 2026 John Karahalis
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Use "strict mode."
#
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail

if (( EUID != 0 )); then
  >&2 echo 'FATAL ERROR: This script must be run as root.'
  exit 1
fi

LOGGED_IN_USER=$(logname)

function os_is_debian_based() {
  [[ -f /etc/debian_version ]]
}

if ! os_is_debian_based; then
  >&2 echo 'FATAL ERROR: This distro is not supported.'
  exit 1
fi

# Install pip if it's not already installed.
#
# pip is needed to install uv system-wide, and a system-wide uv is needed to run
# the setup script.
if ! command -v pip > /dev/null; then
  if os_is_debian_based; then
    apt-get install --assume-yes python3-pip
  fi
fi

# Install uv if it's not already installed.
if ! command -v uv > /dev/null; then
  pip install --break-system-packages uv
fi

# Disable SC2016. We _want_ to use single quotes because we do not want
# $XDG_CONFIG_HOME to be expanded before the command is run.
#
# shellcheck disable=SC2016
LOGGED_IN_USER_XDG_CONFIG_HOME=$(su - "$LOGGED_IN_USER" -c 'echo "$XDG_CONFIG_HOME"')

"$LOGGED_IN_USER_XDG_CONFIG_HOME"/vcsh/hooks-available/dotfiles-openjck-setup/dotfiles-openjck-setup.py "$@"
