require('init.plugins.config.after.ai')
require('init.plugins.config.after.ale')
require('init.plugins.config.after.hipatterns')
require('init.plugins.config.after.mini-clue')
require('init.plugins.config.after.mini-starter')
require('init.plugins.config.after.onedark')
