require('init.plugins.general.ale')
require('init.plugins.general.neogit')
require('init.plugins.general.tabline')
require('init.plugins.general.telescope')
require('init.plugins.general.vim-closetag')
require('init.plugins.general.vim-ripgrep')
require('init.plugins.general.vim-spellsync')
require('init.plugins.general.vim-tmux-navigator')
