#!/usr/bin/env -S uv run --script
#
# /// script
# requires-python = ">=3.12"
# dependencies = ["docopt==0.6.2"]
# ///

import json
import os
import shutil
import subprocess
import sys
import tempfile
import warnings
from collections.abc import Callable
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Dict, List, Literal, TypedDict

from docopt import docopt

# dotfiles-openjck-setup:
# Set up dotfile dependencies.
#
# Usage instructions:
# Install "uv", then run this script.

# MIT License
#
# Copyright (c) 2023, 2024, 2025, 2026 John Karahalis
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Show deprecation warnings.
#
# https://hypirion.com/musings/use-python-for-scripting
warnings.simplefilter("default", DeprecationWarning)

xdg_config_home = os.environ["XDG_CONFIG_HOME"]
xdg_data_home = os.environ["XDG_DATA_HOME"]

directory_bin_local_downloaded = "~/bin/personal/local/downloaded"


class Result(Enum):
    DONE = 1
    ALREADY_DONE = 2
    UNSUPPORTED = 3


class BaseDistro(Enum):
    UNKNOWN = 1
    ALPINE = 2
    ARCH = 3
    DEBIAN = 4
    GENTOO = 5
    REDHAT = 6
    SUSE = 7


@dataclass
class Step:
    term: str
    setup_fn: Callable[[], Result]
    own_activity_output: bool = False


class VcshConfigResult(Enum):
    MODIFIED = 1
    UNMODIFIED = 2


class Packages(TypedDict):
    system: List[str]
    flatpak: Dict[Literal["flathub-verified", "flathub"], List[str]]
    homebrew: List[str]
    pipx: List[str]


class Config(TypedDict):
    packages: Dict[BaseDistro, Packages]
    directories: List[str]


config: Config = {
    "packages": {
        BaseDistro.DEBIAN: {
            "system": [
                "bat",
                "fd-find",
                "flatpak",
                "git",
                "moreutils",
                "pipx",
                "pwgen",
                "renameutils",
                "ripgrep",
                "sd",
                "tmux",
                "toilet",
                "vcsh",
            ],
            "flatpak": {
                "flathub-verified": [
                    "org.mozilla.firefox",
                ],
                "flathub": [],
            },
            "homebrew": [
                # gcc needs to be installed before fzf and perhaps some other formulae.
                "gcc",
                "fpp",
                "fzf",
                "nvim",
                "topgrade",
            ],
            "pipx": [
                "git-fzf",
                "uv",
                "yq",
            ],
        },
    },
    "directories": [
        "~/apps/appimage",
        "~/apps/repos/git",
        "~/bin/personal/local",
        "~/bin/personal/local/temporary",
        directory_bin_local_downloaded,
        f"{xdg_config_home}/bash/init/functions/local",
        f"{xdg_data_home}/fzf",
        "~/LGTD/inboxes/main",
    ],
}


# Run a command, allowing stdout and stderr to be printed to the console.
def run(cmd: str):
    return subprocess.run(cmd, shell=True, check=True)


# Run a command, allowing stderr to be printed to the console, but discarding
# stdout (i.e., not allowing it to print on the console and not capturing it
# for use in this script).
def run_quietly(cmd: str):
    return subprocess.run(cmd, shell=True, stdout=subprocess.DEVNULL)


# Run a command, capturing stdout and allowing stderr to be printed to the
# console.
#
# Pass "check=False" to ignore, rather than raise an error, when a command exits with
# a non-zero exit code.
def run_and_capture(cmd: str, check: bool = True):
    return subprocess.run(
        cmd, shell=True, check=check, text=True, stdout=subprocess.PIPE
    ).stdout.strip()


# Run a command, discarding both stdout and stderr.
def run_silently(cmd: str):
    return subprocess.run(
        cmd,
        shell=True,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )


def set_vcsh_config(config: str, desired_value: str) -> VcshConfigResult:
    # If the configuration option is not set, the command will exit with a non-zero exit
    # code, so pass check=False to ignore that.
    value = run_and_capture(f"vcsh dotfiles-openjck config {config}", check=False)

    if value == desired_value:
        return VcshConfigResult.UNMODIFIED
    else:
        run_quietly(f"vcsh dotfiles-openjck config {config} {desired_value}")
        return VcshConfigResult.MODIFIED


# https://unix.stackexchange.com/a/46086/410447
def get_base_distro() -> BaseDistro:
    distro_markers = {
        "/etc/redhat-release": BaseDistro.REDHAT,
        "/etc/arch-release": BaseDistro.ARCH,
        "/etc/gentoo-release": BaseDistro.GENTOO,
        "/etc/SuSE-release": BaseDistro.SUSE,
        "/etc/debian_version": BaseDistro.DEBIAN,
        "/etc/alpine-release": BaseDistro.ALPINE,
    }

    for filename, base_distro in distro_markers.items():
        if os.path.isfile(filename):
            return base_distro

    return BaseDistro.UNKNOWN


def set_up_packages_system_debian() -> Result:
    to_install: List[str] = []

    for package in config["packages"][BaseDistro.DEBIAN]["system"]:
        if run_silently(f"dpkg -s {package}").returncode != 0:
            to_install.append(package)

    if len(to_install) == 0:
        return Result.ALREADY_DONE
    else:
        # Do not print output on the same line as "Setting up [step name]...".
        #
        # Additionally, remember: "apt" is not meant to be used in scripting. (In this
        # case, I'm sure it doesn't matter, since we're not parsing the output, but
        # strictly speaking, apt-get and friends are recommended for use in scripts
        # instead.)
        print()
        run(f'sudo apt-get install --yes {" ".join(to_install)}')
        return Result.DONE


def set_up_packages_system(base_distro: BaseDistro) -> Result:
    if base_distro == BaseDistro.DEBIAN:
        return set_up_packages_system_debian()
    else:
        return Result.UNSUPPORTED


def set_up_packages_flatpak(base_distro: BaseDistro) -> Result:
    installed_any = False

    # Set up remotes, including one remote for Flathub and one remote for
    # verified flatpaks on Flathub.
    #
    # The system will prompt for the sudo password when doing this, so we can't run
    # these commands quietly.
    run(
        "flatpak remote-add --if-not-exists flathub "
        + "https://dl.flathub.org/repo/flathub.flatpakrepo"
    )
    run(
        "flatpak remote-add --if-not-exists --subset=verified "
        + "flathub-verified https://flathub.org/repo/flathub.flatpakrepo"
    )

    for remote, flatpak_apps in config["packages"][base_distro]["flatpak"].items():
        to_install: List[str] = []

        for flatpak_app in flatpak_apps:
            if run_silently(f"flatpak info {flatpak_app}").returncode != 0:
                to_install.append(flatpak_app)

        if len(to_install) > 0:
            # Do not print output on the same line as "Setting up [step name]...".
            print()
            run(f"flatpak install --noninteractive {remote} " + " ".join(to_install))
            installed_any = True

    if installed_any:
        return Result.DONE
    else:
        return Result.ALREADY_DONE


def set_up_packages_homebrew(base_distro: BaseDistro) -> Result:
    to_install: List[str] = []

    # Install Homebrew itself, if necessary.
    homebrew_install_path = Path("/home/linuxbrew/.linuxbrew")
    if not homebrew_install_path.is_dir():
        run_quietly(
            '/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'  # noqa: E501
        )

    for homebrew_formula in config["packages"][base_distro]["homebrew"]:
        if run_silently(f"brew list {homebrew_formula}").returncode != 0:
            to_install.append(homebrew_formula)

    if len(to_install) == 0:
        return Result.ALREADY_DONE
    else:
        # Do not print output on the same line as "Setting up [step name]...".
        print()
        run(f'brew install {" ".join(to_install)}')
        return Result.DONE


def set_up_packages_pipx(base_distro: BaseDistro) -> Result:
    to_install: List[str] = []

    pipx_list = json.loads(run_and_capture("pipx list --json"))

    for pipx_package in config["packages"][base_distro]["pipx"]:
        if pipx_package not in pipx_list["venvs"]:
            to_install.append(pipx_package)

    if len(to_install) == 0:
        return Result.ALREADY_DONE
    else:
        # Do not print output on the same line as "Setting up [step name]...".
        print()
        run(f'pipx install {" ".join(to_install)}')
        return Result.DONE


def set_up_directories() -> Result:
    created_any = False

    for directory in config["directories"]:
        path = Path(directory).expanduser()
        if not path.is_dir():
            path.mkdir(parents=True)
            created_any = True

    if created_any:
        return Result.DONE
    else:
        return Result.ALREADY_DONE


# This installs docopts. Note the s at the end of the word.
#
# This installs docopts (notice the s at the end) not docopt (no s).
#
# docopt (no s), which is used by this script itself, is a Python package that helps
# with writing help text and makes parsing arguments very easy. docopts (with the s)
# does the same thing for shell scripts, and it's used by all of my shell scripts except
# the bootstrap script.
def set_up_docopts() -> Result:
    if shutil.which("docopts") is not None:
        return Result.ALREADY_DONE
    else:
        with tempfile.TemporaryDirectory(delete=False) as tmp_dir:
            # Do not print output on the same line as "Setting up [step name]...".
            print()
            run(f"git clone https://github.com/docopt/docopts.git {tmp_dir}/docopts")

            # For some reason, running `{tmp_dir}/docopts` directly does not work. You
            # really do need to cd into the directory first.
            run(f"cd {tmp_dir}/docopts && ./get_docopts.sh")

            docopts_bin_destination = Path(directory_bin_local_downloaded).expanduser()
            shutil.copy(f"{tmp_dir}/docopts/docopts", docopts_bin_destination)

            return Result.DONE


def set_up_vcsh() -> Result:
    modified_config = False

    show_untracked_result = set_vcsh_config("status.showUntrackedFiles", "no")
    if show_untracked_result == VcshConfigResult.MODIFIED:
        modified_config = True

    sparse_checkout_result = set_vcsh_config("core.sparseCheckout", "true")
    if sparse_checkout_result == VcshConfigResult.MODIFIED:
        modified_config = True

    # Note that the final newline (the newline after the last line of text) is
    # not a mistake, and it's not required by Python syntactically. It's there
    # so that the file ends with a newline, as Unix conventions require.
    sc_file_contents = """*
!/README.md
!/LICENSE
!/docs/**
"""

    sc_filename = (
        f"{xdg_config_home}/vcsh/repo.d/dotfiles-openjck.git/info/sparse-checkout"
    )

    if (not os.path.isfile(sc_filename)) or open(
        sc_filename, mode="r"
    ).read() != sc_file_contents:
        sc_file = open(sc_filename, mode="w")
        sc_file.write(sc_file_contents)
        sc_file.close()
        run("vcsh dotfiles-openjck checkout")
        modified_config = True

    if modified_config:
        return Result.DONE
    else:
        return Result.ALREADY_DONE


def set_up_tmux() -> Result:
    tpm_path = Path("~/.tmux/plugins/tpm").expanduser()
    tpm_path_str = tpm_path.absolute().as_posix()

    if tpm_path.is_dir():
        return Result.ALREADY_DONE
    else:
        # Do not print output on the same line as "Setting up [step name]...".
        print()

        # Install tpm.
        run(f"git clone --quiet https://github.com/tmux-plugins/tpm {tpm_path_str}")

        # Install plugins.
        run(f"{tpm_path_str}/bin/install_plugins")

        return Result.DONE


def run_steps(steps: List[Step]):
    longest_term_length = max(map(lambda s: len(s.term), steps))

    for step in steps:
        run_step(step, longest_term_length)

    return 0


def run_step(step: Step, longest_term_length: int):
    min_dots = 3  # Always show at least 3 dots after a term, even the longest term.
    pad_length = longest_term_length + min_dots
    term_and_dots = step.term.ljust(pad_length, ".")

    print(f"Setting up {term_and_dots} ", end="", flush=True)

    result = step.setup_fn()

    match result:
        case Result.DONE:
            if not step.own_activity_output:
                print("done.")
        case Result.ALREADY_DONE:
            print("already done.")
        case Result.UNSUPPORTED:
            print("unsupported.")


def main():
    filename = os.path.basename(__file__)
    help_text = f"""
Set up the packages, directories, plugin managers, and other dotfile
dependencies used across machines.

This script is idempotent and can therefore be run multiple times without
affecting the result, assuming the script's implementation does not change
between invocations. It should be rerun occasionally or whenever important
details change, like configured packages or configured directories.

Usage:
  {filename}
  {filename} -h | --help

Options:
  -h, --help
      Show this documentation
""".strip()

    docopt(help_text)

    base_distro = get_base_distro()

    steps = [
        Step("packages (system)", lambda: set_up_packages_system(base_distro), True),
        Step("packages (flatpak)", lambda: set_up_packages_flatpak(base_distro), True),
        Step(
            "packages (homebrew)", lambda: set_up_packages_homebrew(base_distro), True
        ),
        Step("packages (pipx)", lambda: set_up_packages_pipx(base_distro), True),
        # Set up directories before docopts else because set_up_docopts requires one of
        # those directories to exist.
        Step("directories", set_up_directories),
        Step("docopts", set_up_docopts, True),
        Step("vcsh", set_up_vcsh),
        Step("tmux", set_up_tmux, True),
    ]

    return run_steps(steps)


if __name__ == "__main__":
    sys.exit(main())
