# vim: filetype=tmux

# Forcefully enable hyperlink support.
#
# As of 2026-07-21, it seems this is necessary because tmux doesn't correctly
# identify gnome-terminal as supporting hyperlinks. Therefore, in the future,
# forcefully enabling hyperlink support as we do here may not be necessary.
#
# https://stackoverflow.com/a/79306046/715866
set -as terminal-features ",*:hyperlinks"
