.PHONY: format lint

format:
	# Calling "shfmt" this way ensures that the "shfmt" function is called, which
	# is important, because it sets custom formatting options.
	bash -i -c "shfmt ."

lint:
	# Calling "shfmt" this way ensures that the "shfmt" function is called, which
	# is important, because it sets custom formatting options.
	bash -i -c "shfmt --list ."
