# Automatically start Zellij.
#
# This code was generated by the following command:
# zellij setup --generate-auto-start bash
#
# See the following for more information:
# https://zellij.dev/documentation/integration.html#bash
if [[ -z "$ZELLIJ" ]]; then
  if [[ "$ZELLIJ_AUTO_ATTACH" == "true" ]]; then
    zellij attach -c
  else
    zellij
  fi

  if [[ "$ZELLIJ_AUTO_EXIT" == "true" ]]; then
    exit
  fi
fi
