require('init.plugins.colorschemes.catppuccin')
require('init.plugins.colorschemes.halcyon')
require('init.plugins.colorschemes.monokai-pro')
require('init.plugins.colorschemes.nightfox')
require('init.plugins.colorschemes.onedark')
require('init.plugins.colorschemes.tokyonight')
