#!/usr/bin/env bash

# Nautilus extension:
# Remove empty directories (rmdir)
#
# Remove an empty directory. If a non-empty directory or a file is selected,
# show an error message instead. More than one item can be selected at a time.

# MIT License
#
# Copyright (c) 2026 John Karahalis
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Use Bash's unofficial "strict mode."
#
# The suggested change to the value of "IFS" is not applied because it doesn't
# appear to be necessary when best practices and ShellCheck's advice are being
# followed. In the examples the author provides, the preferred results occur
# even when "IFS" is unchanged, as long as variables are double-quoted, which is
# a best practice and a ShellCheck recommendation.
#
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -o errexit
set -o nounset
set -o pipefail

NOT_DIRECTORIES=()
NOT_EMPTY=()
FAILED=()

NUM_SELECTIONS=0

# The last line of $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS is a newline, so this
# pattern of looping is needed to avoid running the body of the loop one extra
# time where "$DIRECTORY" is the empty string.
#
# We could just check if "$DIRECTORY" is the empty string at the beginning of
# the body of the loop, but this pattern is more general-purpose, and it works
# in cases where the body truly shouldn't be run at all for that final newline.
#
# https://superuser.com/a/284226
while IFS= read -r DIRECTORY || [[ -n $DIRECTORY ]]; do
  NUM_SELECTIONS=$((NUM_SELECTIONS + 1))

  if [[ ! -d "$DIRECTORY" ]]; then
    NOT_DIRECTORIES+=("$DIRECTORY")
    continue
  fi

  if [[ -n "$( ls --almost-all "$DIRECTORY" )" ]]; then
    NOT_EMPTY+=("$DIRECTORY")
    continue
  fi

  if ! rmdir "$DIRECTORY"; then
    FAILED+=("$DIRECTORY")
    continue
  fi
done < <(printf '%s' "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS")

ERROR_MESSAGE=''

function build_error_message_section() {
  local -n ARRAY=$1
  local SINGLE_SELECTION_MESSAGE=$2
  local MULTIPLE_SELECTIONS_HEADER=$3

  if (( ${#ARRAY[@]} == 0 )); then
    return
  fi

  if (( NUM_SELECTIONS == 1 )); then
    ERROR_MESSAGE=$SINGLE_SELECTION_MESSAGE
  else
    if [[ -n $ERROR_MESSAGE ]]; then
      ERROR_MESSAGE+=$'\n\n'
    fi

    ERROR_MESSAGE+="${MULTIPLE_SELECTIONS_HEADER}:"$'\n\n'

    for ELEMENT in "${ARRAY[@]}"; do
      ERROR_MESSAGE+="    $ELEMENT"$'\n'
    done
  fi
}

build_error_message_section \
  NOT_EMPTY \
  'Directory is not empty.' \
  'The following directories are not empty'

build_error_message_section \
  NOT_DIRECTORIES \
  'Item is not a directory.' \
  'The following items are not directories'

build_error_message_section \
  FAILED \
  'Item failed to be removed for unknown reason.' \
  'The following items failed to be removed for unknown reasons'

if [[ -n $ERROR_MESSAGE ]]; then
  zenity --error --text "$ERROR_MESSAGE"
fi
